language: php

sudo: false

php:
  - 5.6
  - 7
  - 7.1

env:
  global:
    - BUILD_DIR=$TRAVIS_BUILD_DIR/travis-ci

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

mysql:
  database: drupal
  encoding: utf8

cache:
  directories:
  - $HOME/.composer/cache

before_install:
  - composer self-update
  - git config --global github.accesstoken $GITHUB_OAUTH_TOKEN

install:
  # Build Drupal and add the package under test as a dependency.
  - mkdir module
  - cp -R *.* module
  - cd $BUILD_DIR
  - composer install

  # Install Drupal and Simpletest.
  - cd $BUILD_DIR/web
  - /usr/bin/env PHP_OPTIONS="-d sendmail_path=`which true`" ../vendor/bin/drush si --db-url=mysql://root:@localhost:/drupal testing -y
  - ../vendor/bin/drush en simpletest -y

  # Start a web server.
  - cd $BUILD_DIR/web
  - ../vendor/bin/drush runserver 127.0.0.1:8080 &

script:
  # Run unit and kernel tests.
  - export SIMPLETEST_DB="mysql://root@127.0.0.1/drupal"
  - $BUILD_DIR/vendor/bin/phpunit -c $TRAVIS_BUILD_DIR/phpunit.xml.dist --bootstrap $BUILD_DIR/web/core/tests/bootstrap.php --verbose --debug
